### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by snacks-yummy** [unknown-o/genshin-check-in#3]
阿里云函数报错和pycharm都会报错“IndexError: list index out of range

**Comment by unknown-o** [comment]
现在提issues都可以不带脑子了么？
自己都不看看是因为什么导致的报错，是不是你使用方式不对？
我明明都写了使用示例，是没长眼睛么？

**Comment by snacks-yummy** [comment]
> 现在提问题都可以不带脑子了么？自己都不看看是因为什么导致的报错,是不是你使用方式不对？我明明都写了使用示例,是没长眼睛么？
上一版本是正常使用的....
